spring.application.name=backend
spring.profiles.active=dev

# =========================
# DATASOURCE (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/workhub?serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ?? ?? ??? ?? ON
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# jwt
jwt.secret=5853ae85c785bb1f1ce5eed3d70e610a3577247142d813370b52f8eb66e2644b
jwt.access-token-expiration-ms=3600000
jwt.issuer=foongdoll

# =========================
# SPRINGDOC / SWAGGER
# =========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


# ?? ?? ?? (traceId/userId/path ??)
/logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [traceId=%X{traceId}] [userId=%X{userId}] [path=%X{path}] %msg%n

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=healim5028@gmail.com
spring.mail.password=thslffcnmumjwczq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
